site_name: K2 Plus Custom Firmware
site_description: Documentation for K2 Plus Custom Firmware
site_url: https://kennethDoerflein.github.io/k2-plus-custom-firmware/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Use dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Use light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Install: install.md
  - Calibration: calibration.md
  - OrcaSlicer: setup.md
  - CFS and RFID: cfs.md
  - Error explanation: error-explanation.md
  - Updates & Recovery: updates-recovery.md
  - Reference:
      - Command Reference: command-reference.md
      - Config Reference: config-reference.md
